export const FETCH_AIRPORTS = "FETCH_AIRPORTS";
export const FETCH_FLIGHTS = "FETCH_FLIGHTS";
export const FETCH_FLIGHTS_BY_SEARCH = "FETCH_FLIGHTS_BY_SEARCH";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
